### ISSUE TITLE
5.05 support?

### ISSUE THREAD

**Issue by spotanjo3** [ps3120/ps3120.github.io#1]
I would like to report for 5.05 if there is a bug or an issue. I would like to test it if you can support 5.05 as well ? Keep up the good work.

**Comment by ps3120** [comment]
I can add support for 5.05 but 5.05 is already fast and stable

**Comment by spotanjo3** [comment]
I know but it would be great since golden is update. I can test it and report to you for golden update, yeah ?

**Comment by ps3120** [comment]
You need goldhen update?

**Comment by spotanjo3** [comment]
I have been used previously golden because I had a different link to used. I wonder if I would like to use yours and see if yours are better than other site that I used. Sorry about my English. ^_^

**Comment by ps3120** [comment]
http://consolepcmod.altervista.org/multiHen/ 
Use this it is always uploaded by me

**Comment by spotanjo3** [comment]
With the latest golden released update ?

**Comment by ps3120** [comment]
Yes

**Comment by spotanjo3** [comment]
Awesome. Thank you! I will report back to you later on this one if you want me to?

**Comment by ps3120** [comment]
Ok

**Comment by spotanjo3** [comment]
> http://consolepcmod.altervista.org/multiHen/ Use this it is always uploaded by me

Hello. Sorry to keep you delay. I promised to be here and I did. Yes, it works great. And I have a question. Do you think that it is a good idea to add https for "s" in it to be secure or its not necessarily for the reason ?

**Comment by ps3120** [comment]
it does not make sense

**Comment by spotanjo3** [comment]
Thank you. Much appreciated.
